graph_indir: /home/abdel/IRIS_HEP/trackml_data/processed_plus_pyg_small_test
output_dir: /home/abdel/IRIS_HEP/manual_GNN_conversion/roc_plots
model: 
  state_dict: trained_models/IN_pyg_small_add_source_to_target_8_state_dict.pt
  aggr: add
  flow: source_to_target
  n_neurons: 8
