# Input/output configuration
input_dir: /home/abdel/IRIS_HEP/trackml_data/raw
output_dir:  /home/abdel/IRIS_HEP/trackml_data/pipeline_benchmark

n_files: 1800

# Graph building configuration
selection:
    pt_min: 2 # GeV
    phi_slope_max: 0.0006 
    z0_max: 15000 
    n_phi_sections: 8
    n_eta_sections: 2
    eta_range: [-5, 5]
    endcaps: true
    phi_reflect: false
    remove_intersecting_edges: true
